### ISSUE TITLE
Does not parse links for Google feedburner feeds

### ISSUE THREAD

**Issue by katiebeltramini** [bobby-brennan/rss-parser#10]
I'm trying to parse a few feedburner feeds, for example:

http://feeds.feedburner.com/blogspot/lQlzL

The link that is returned is of the: type="application/atom+xml".  I'm not able to target the link to go to the type="text/html".   The RSS feed also has feedburner:origLinkhttp://googleadsdeveloper.blogspot.com/2016/06/register-now-for-fall-2016-adwords-api.html/feedburner:origLink which would work as well for the link.  This may be too specific of an issue, but still thought I'd try.

**Comment by bobby-brennan** [comment]
Sorry, not sure I understand the issue here. I added a test case for the feedburner link above (by downloading the XML to a local file) and it seems to parse fine.  Why do you need type="text/html"?

**Comment by katiebeltramini** [comment]
When I used your library on a feed like: http://feeds.feedburner.com/blogspot/lQlzL, there are multiple link types.  When I used your library, the link that went with the titles led to pages like:

https://www.blogger.com/feeds/7815614485808579332/posts/default/8394866751819460570

vs.


http://googleadsdeveloper.blogspot.com/2016/06/adwords-and-dfp-java-client-library.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+blogspot%2FlQlzL+%28Google+Ads+Developer+Blog+-+AdWords+API%29&utm_content=FeedBurner

However, I ended up using something else to get around this issue.

**Comment by bobby-brennan** [comment]
Marking as closed, I think with `customFields` this should be fixed.
