### ISSUE TITLE
Invalid character in RSS XML exception

### ISSUE THREAD

**Issue by 7Ds7** [bobby-brennan/rss-parser#11]
I wen't into the problem of parsing certain RSS feeds that did not have a valid XML structure due to illegal characters. 
The problem might be more personal and without interest to the rss-parser package even so i expose it here.
My problem was that i scrapped a few RSS channels and whenever  one of these channels had invalid XML (which happens quite often) the app fully stopped.

The exception is thrown in this line https://github.com/bobby-brennan/rss-parser/blob/master/index.js#L106 , my question is why is it not throw a error as the callback parameter like so https://github.com/7Ds7/rss-parser/blob/master/index.js#L107 ?

It would be verbose anyway and it would not stop the app with one exception. Is there a reason more deep that i can figure for for it to throw this exception? Is there any other way to prevent this exception without changing rss-parser source ?

Anyway many thanks for this package totally worth it :)

**Comment by bobby-brennan** [comment]
Hey, thanks for the report, you make a good point!

This should be fixed in https://github.com/bobby-brennan/rss-parser/commit/f3b73888b2d8b334fe80e5a9e34bec6e18273d48
