### ISSUE TITLE
Cannot access data on custom fields

### ISSUE THREAD

**Issue by ztratify** [bobby-brennan/rss-parser#110]
I'm using the [rss-parser](https://www.npmjs.com/package/rss-parser) javascript package to parse the XML of a [Craigslist feed](https://vancouver.craigslist.org/search/cta?format=rss&query=%22motor+home%22) like this:

```
<?xml version="1.0" encoding="UTF-8"?>
...
<item rdf:about="https://vancouver.craigslist.org/nvn/cto/d/squamish-trade-my-car-for-your-motor/6871699755.html">
  <title><![CDATA[Trade my car for your motor home (Squamish)]]></title>
  <link>https://vancouver.craigslist.org/nvn/cto/d/squamish-trade-my-car-for-your-motor/6871699755.html</link>
  <description><![CDATA[Looking to trade my 2004 Chrysler Sebring for a perhaps older but good shape motorhome]]></description>
  <dc:date>2019-04-21T17:23:31-07:00</dc:date>
  <dc:language>en-us</dc:language>
  <dc:rights>copyright 2019 craigslist</dc:rights>
  <dc:source>https://vancouver.craigslist.org/nvn/cto/d/squamish-trade-my-car-for-your-motor/6871699755.html</dc:source>
  <dc:title><![CDATA[Trade my car for your motor home (Squamish)]]></dc:title>
  <dc:type>text</dc:type>
  <enc:enclosure resource="https://images.craigslist.org/01010_eszS9ZP8p2c_300x300.jpg" type="image/jpeg"/>
  <dcterms:issued>2019-04-21T17:23:31-07:00</dcterms:issued>
</item>
...
```

Which returns this json as expected:

```
{
    "items": [
        {
            "date": "2019-04-21T17:23:31-07:00",
            "language": "en-us",
            "rights": "copyright 2019 craigslist",
            "source": "https://vancouver.craigslist.org/nvn/cto/d/squamish-trade-my-car-for-your-motor/6871699755.html",
            "title": "Trade my car for your motor home (Squamish)",
            "link": "https://vancouver.craigslist.org/nvn/cto/d/squamish-trade-my-car-for-your-motor/6871699755.html",
            "dc:date": "2019-04-21T17:23:31-07:00",
            "content": "Looking to trade my 2004 Chrysler Sebring for a perhaps older but good shape motorhome",
            "contentSnippet": "Looking to trade my 2004 Chrysler Sebring for a perhaps older but good shape motorhome",
            "isoDate": "2019-04-22T00:23:31.000Z"
        },
      ...
    ]
}
```

However I want rss-parser to also return the custom field `enc:enclosure` (so I'm passing the custom field option to each item when constructing the Parser as outlined in the docs):

```
  const parser = new Parser({
    customFields: {
      item: ['enc:enclosure']
    }
  });
```

And the json gets returned to me just fine!

```
    "items": [
        {
            "date": "2019-04-21T17:23:31-07:00",
            ...
            "enc:enclosure": {
                "$": {
                    "resource": "https://images.craigslist.org/01010_eszS9ZP8p2c_300x300.jpg",
                    "type": "image/jpeg"
                }
            },
        },
    ]
```

But here's where it gets weird... ಠ_ಠ

I can access the "enc:enclosure" data no problem using `feed.items[0]["enc:enclosure"]` as you'd expect. But as soon as I try to go one level deeper using `feed.items[0]["enc:enclosure"]["$"]` or `feed.items[0]["enc:enclosure"].$` I'm getting an error that now suggests `feed.items[0]["enc:enclosure"]` is undefined??

```
TypeError: Cannot read property '$' of undefined
    at feed.items.forEach.item (/Users/.../controllers/scrape.js:20:23)
    at Array.forEach ()
    at exports.craigslist (/Users/.../controllers/scrape.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Going any deeper than the custom field seams to throw an error.

**Comment by bobby-brennan** [comment]
That does seem strange. Can you share a gist that reproduces this?

**Comment by ztratify** [comment]
Sorry! I'm definitely new to this so not sure how to make a node gist. I've recreated the problem using Glitch: https://glitch.com/edit/#!/join/b9677513-5b5c-4b1e-9eaf-1b1d63545018

Feel free to mess around :)

**Comment by ztratify** [comment]
I should mention I'm now getting the same error using [xml2js](https://www.npmjs.com/package/xml2js) so it must be a dependency setting? I'm looking into it!

It gets weirder though... You can see on this line that I can access individual custom field attributes outside of the loop: https://glitch.com/edit/#!/foul-reminder?path=server.js:29:7

As soon as I loop over the items (using forEach or map) I can't access the attributes! It also doesn't seam to be a side effect of custom fields, but attributes in general from my testing on xml2js. Am I missing something obvious? ¯\\_(シ)\_/¯

**Comment by ztratify** [comment]
Solved. [As mentioned on stackoverflow](https://stackoverflow.com/questions/55975086/cannot-access-xml-attributes-when-looping-over-items-of-xml2js-parsed-json) I'm assuming that the enclosure property exists when in one case it does not, so just a simple javascript error.... 

Really sorry for wasting your time!

**Comment by bobby-brennan** [comment]
No problem - glad you solved it!
