### ISSUE TITLE
Does not support IE11

### ISSUE THREAD

**Issue by cnbillow** [bobby-brennan/rss-parser#113]
**The code:**
const RSSParser = require('rss-parser');
const parser = new RSSParser();
parser.parseString(data)

**The errors in Internet Explorer 11:**
SCRIPT1002: Syntax error
vendor.js (149004,1)

class Parser {
  constructor(options={}) {

**Comment by bobby-brennan** [comment]
Try using the browser distribution: https://github.com/bobby-brennan/rss-parser/blob/master/dist/rss-parser.min.js

If you're using `require`, you'll need to look at your transpiler settings for browser compatibility.
