### ISSUE TITLE
Feature Request - Add types for Typescript

### ISSUE THREAD

**Issue by St1fle** [bobby-brennan/rss-parser#115]
Would be really nice if there were types as part of [DefinitelyTyped](https://github.com/DefinitelyTyped) so the library is easier to use with Typescript. Although, tbh, it's not a biggie. Just a nuisance to have to type the feed definitions 😄

**Comment by bobby-brennan** [comment]
We've got an index.d.ts file - does that not work for you?

**Comment by St1fle** [comment]
Yes, this was my bad, I only realised the types were at bottom of the index file, a simple `import Parser from './rss-parser';` works perfectly fine.

I think my mistake was just assuming because there were no types under `DefinitelyTyped` that this 
didn't had support for typescript, I should've look at the source code. My bad, apologies! Feel free to close this.

**Comment by bobby-brennan** [comment]
No problem, thanks!
