### ISSUE TITLE
Problem parsing feed

### ISSUE THREAD

**Issue by MorningSleeper** [bobby-brennan/rss-parser#116]
Hi, using 3.7.1, trying to access feed at following URL which tests as a valid RSS feed. I retrieve the output using request fine and then send it to parseString which produces no error but feed.length is undefined? Any idea why?

https://www.sec.gov/rss/litigation/suspensions.xml

**Comment by bobby-brennan** [comment]
Can you share your code? `feed.items` is full for me.

**Comment by MorningSleeper** [comment]
Code is below, I thought one could check length of feed to see if any results but on this feed it appears one needs to check length of feed.items?

```
var Parser = require('rss-parser');
var rssParser = new Parser();

// html contains rss feed contents

rssParser.parseString(html, function (error, feed) {

if (!error) {
// feed.length = undefined here
// feed.items.length = 61 here
}

});
```
