### ISSUE TITLE
jspm compatibility

### ISSUE THREAD

**Issue by kst83** [bobby-brennan/rss-parser#16]
I tried using this library using jspm.
The file loads, the callback function of parseURL is never called.
Is this an incompatibility with jspm?
Any ideas?

**Comment by bobby-brennan** [comment]
I'm not familiar with jspm, but as long as it loads the js file in `/dist/rss-parser.js` everything should work normally.

There are some issues in the browser with CORS - most public RSS feeds don't allow you to fetch them from the browser without a proxy.  The callback should still be called though.

Happy to help debug if you're able to share more details.

**Comment by bobby-brennan** [comment]
Marking as closed - if anyone else has issues with jspm feel free to re-open
