### ISSUE TITLE
Parse Custom Fields

### ISSUE THREAD

**Issue by vivekiran** [bobby-brennan/rss-parser#25]
Is there any way to parse custom fields from RSS feed.

**Comment by bobby-brennan** [comment]
This would be a great feature. `parseURL` already has an optional `settings` argument which could be added to `parseString` and `parseFile`.  For example:

```js
var settings = {
  customFields: {
    feed: ['otherTitle', 'extendedDescription'],
    item: ['coAuthor'],
  }
}
parser.parseFile('./rss.xml', settings, (err, result) => {
  console.log(result.feed.extendedDescription);
})
```

Pull requests welcome!

**Comment by vivekiran** [comment]
Pull Request #27
