### ISSUE TITLE
Not found dependency

### ISSUE THREAD

**Issue by PG-Andrey** [bobby-brennan/rss-parser#28]
This dependency was not found:
* fs in ./~/rss-parser/index.js

**Comment by bobby-brennan** [comment]
Are you using it in the browser? If so, you'll want to use ./dist/rss-parser.min.js

**Comment by bobby-brennan** [comment]
If you're using webpack, you can also check out this issue for a solution:

https://github.com/bobby-brennan/rss-parser/issues/20

**Comment by bobby-brennan** [comment]
Closing this - lmk if you're still seeing this issue.
