### ISSUE TITLE
Encoding special characters (ISO 639-1)

### ISSUE THREAD

**Issue by cedevita** [bobby-brennan/rss-parser#30]
Hello,

I use rss-parser on some feeds in the Serbian language, which has several **special characters**, like: `Š, Č, Ć, Ž`.
All of these are (in rss-parser 2.10.1) replaced with `\ufffd`.

Is there any way encoding can be improved to cover these (latin-extended, ISO 639-1 codes) characters? Same would apply to several other languages - Slovenian, Croatian, Bosnian, etc.

I love the simplicity of use, despite the lack of async/await support :) but I will have to find an alternative if I can't solve this encoding issue.

**Comment by bobby-brennan** [comment]
I believe this is coming from https://github.com/fb55/entities. 

`item.content` contains the unmodified HTML, which should still have the special characters fully encoded. `item.contentSnippet` is just a modified version of `item.content` which removes HTML tags and decodes entities like `&nbsp;`. Fields like `item.title` and `item.description` should also still have the original encoded chars.

I can see if `entities` can be modified to fix contentSnippet - do you have a sample feed you can share?

**Comment by cedevita** [comment]
Here, this one: [http://www.b92.net/info/rss/sport.xml](http://www.b92.net/info/rss/sport.xml) for example.

From that feed, here is before and after.
Before:
```
<description>
Kineski plivač Sun Jang osvojio je zlatnu medalju u trci na 400 metara slobodnim stilom na Svetskom prvenstvu u Budimpešti. On je u današnjem finalu iza sebe ostavio Australijanca Maka Hortona koji je doplivao do srebra (3:43,85), dok je bronzana medalja otišla u ruke Italijanu Gabrijelu Detiju (3:43,93).
</description>
```
After:
` "Kineski pliva\ufffd Sun Jang osvojio je zlatnu medalju u trci na 400 metara slobodnim stilom na Svetskom prvenstvu u Budimpe\ufffdti.  On je u dana\ufffdnjem finalu iza sebe ostavio Australijanca Maka Hortona koji je doplivao do srebra (3:43,85), dok je bronzana medalja oti\ufffdla u ruke Italijanu Gabrijelu Detiju (3:43,93)."`

```
plivač -> pliva\ufffd
Budimpešti -> Budimpe\ufffdti
današnjem -> dana\ufffdnjem
otišla -> oti\ufffdla 
```

**Comment by bobby-brennan** [comment]
Ahh the issue seems to be that b92 is using `windows-1250` encoding instead of `utf-8`.  Putting ISO 639-1 special characters into a UTF-8 encoded RSS feed seems to work fine.

I'm open to suggestions on how to fix, but it looks like converting your feeds to utf-8 using [iconv](https://github.com/bnoordhuis/node-iconv) before passing them to rss-parser is the best way to go.

**Comment by fmsf** [comment]
This looks like a bug. The parser should respect the encoding specified in the XML of the feed:
i.e.: ```<?xml version="1.0" encoding="ISO-8859-1"?>```

Here's an example: http://feeds.jn.pt/JN-Ultimas/

**Comment by bobby-brennan** [comment]
You're right, we should set the encoding based on the content-type header if available.

I will try and put this into v3, as well as an option for specifying encoding manually. In the meantime, you can always download the URL outside of rss-parser and use `parseString`.

**Comment by bobby-brennan** [comment]
Working now in v3: `npm install https://github.com/bobby-brennan/rss-parser#v3`

**Comment by bobby-brennan** [comment]
V3 is now merged, which will use the encoding in content-type if available.

Thanks for the report!

**Comment by fmsf** [comment]
That's awesome! thanks
