### ISSUE TITLE
Newer than 2.7 versions throwing Buffer.allocUnsafe

### ISSUE THREAD

**Issue by lashidalgo** [bobby-brennan/rss-parser#34]
**Bug**

When doing `npm install` and pulling 2.10.2 (I believe this also happens in newer than 2.7 too) the browser is throwing `Buffer.allocUnsafe`
![screen shot 2017-08-22 at 11 33 16 am](https://user-images.githubusercontent.com/11464278/29581312-b9da14b4-872d-11e7-91a4-85ad27b9d862.png)
![screen shot 2017-08-22 at 11 38 11 am](https://user-images.githubusercontent.com/11464278/29581520-69714c9e-872e-11e7-99b6-360e6ebeba5f.png)

**Notes**

`Buffer` is a `node` specific API. Since is not available in the browser It'll throw the exception. Maybe is the way the package is been build and packaged?

**Comment by bobby-brennan** [comment]
Thanks for the report! This is fixed in 2.10.3

#### Details
* Switched from using Grunt to webpack
* Added test for browser using Chrome's puppeteer

**Comment by lashidalgo** [comment]
Thanks @bobby-brennan ! that was super fast!
