### ISSUE TITLE
Latest Update Breaks Safari

### ISSUE THREAD

**Issue by arist0tl3** [bobby-brennan/rss-parser#38]
Safari doesn't allow `const` declarations in `use strict` mode, which is causing a white screen when trying to use this package.

Rolling back to 2.10.2 resolved the issue. The line in question is below. Will submit a PR.

https://github.com/bobby-brennan/rss-parser/blob/5d290bd139f5f63ec463196b505027f8f92049e0/index.js#L215

**Comment by bobby-brennan** [comment]
Thanks! Fix is published as 2.10.5.

Out of curiosity, how are you using this in-browser? `dist/rss-parser.js` should have `const` removed after going through webpack.

**Comment by bobby-brennan** [comment]
Also, if you have any ideas on how best to test for this, let me know.

**Comment by arist0tl3** [comment]
You are right! I'm using it in Meteor, in a method. Not sure if you know Meteor, but methods are made available to both client and server (so that the client can do optimistic updates). Things were working out of the box, so I didn't write any code to specifically limit the function to the server side. But then this latest update obviously caused a problem, as the client-side evaluation on safari was complaining.

What I'd normally do is wrap code like this in a server-only block if the client complains. But in 2.10.2 (where I started), things were working so I didn't think a wrap was necessary.

Let me know if you have any questions -- I think this is probably an edge case, as typically the client wouldn't be evaluating server-side code.

**Comment by bobby-brennan** [comment]
Ahh that makes sense. I'd been considering rewriting index.js with ES6 features since `dist/` files will be translated using babel, but it's good to know that it'd break some workflows. If I do go that route I'll release it as a `major` version so it won't break Meteor builds.

Thanks for reporting/fixing!
