### ISSUE TITLE
element names that include the colon ":" symbol are being skipped?

### ISSUE THREAD

**Issue by Ev1dentFir3** [bobby-brennan/rss-parser#40]
I'm parsing a live rss feed for a games in game alerts, and some of the items have elements that are called "wf:faction" and "wf:expiry"

![](https://i.gyazo.com/065696e47ccabcf6e9ce368af567827c.png)

here is what I'm getting out of that element

![](https://i.gyazo.com/8775e2e98b0162bc6f5b11255a303392.png)

If you want to test it here is the rss feed itself http://content.warframe.com/dynamic/rss.php

I'm using rss-parser 2.10.4

**Comment by bobby-brennan** [comment]
rss-parser only extracts a whitelist of fields, but you [can pass in other fields](https://github.com/bobby-brennan/rss-parser#custom-fields) you want to extract. For example, the below will extract the `wf:expiry` field as `expiry`:

```js
var options = {
  customFields: {
    item: [
      ['wf:expiry', 'expiry'],
    ]
  }
}

parser.parseURL('http://content.warframe.com/dynamic/rss.php', options, (err, data) => {
  console.log(data.feed.entries[0].expiry);
})
```

Also, note that this functionality was only implemented for Atom feeds in 2.10.6

Hope that helps!

**Comment by Ev1dentFir3** [comment]
awesome, thanks, I'll give that a shot

**Comment by Ev1dentFir3** [comment]
Worked perfectly, thanks for the quick response!
