### ISSUE TITLE
Doesn't work with webpack

### ISSUE THREAD

**Issue by skhilko** [bobby-brennan/rss-parser#41]
`rss-parser` fails during compilation when used in a project with `webpack` due to `fs` dependency.

![screen shot 2017-09-22 at 10 35 22 am](https://user-images.githubusercontent.com/970479/30757090-2ba91ce0-9f82-11e7-8ae6-26f7c6503db2.png)

**Comment by bobby-brennan** [comment]
See this issue for a solution: https://github.com/bobby-brennan/rss-parser/issues/20

I'm going to get rid of `parseFile` in v3 for this reason, since it's just a simple wrapper around fs.

**Comment by bobby-brennan** [comment]
`parseFile` is now removed in version 3.0.0, so this should be fixed.
