### ISSUE TITLE
when item contains many "link" fields

### ISSUE THREAD

**Issue by stephen-walsh** [bobby-brennan/rss-parser#42]
Having a issues where the RSS feed contains the following

```
<link rel="replies" type="application/atom+xml" href="http://testing.googleblog.com/feeds/3343661551924942594/comments/default" title="Post Comments" />
<link rel="replies" type="text/html" href="http://testing.googleblog.com/2017/07/evolution-of-gtac-and-engineering.html#comment-form" title="4 Comments" />
<link rel="edit" type="application/atom+xml" href="http://www.blogger.com/feeds/15045980/posts/default/3343661551924942594" />
<link rel="self" type="application/atom+xml" href="http://www.blogger.com/feeds/15045980/posts/default/3343661551924942594" />
<link rel="alternate" type="text/html" href="http://feedproxy.google.com/~r/blogspot/RLXA/~3/ptSfzdHRC4s/evolution-of-gtac-and-engineering.html" title="Evolution of GTAC and Engineering Productivity" />


```
It would be nice if i could specify that the link i want is the  type="text/html" 

right now all i get it 
```
{
	"link": "http://testing.googleblog.com/feeds/3343661551924942594/comments/default",
}
```

**Comment by bobby-brennan** [comment]
Interesting...do you have a link to the original RSS feed? I'll take a look.

**Comment by stephen-walsh** [comment]
Thanks Bobby for a VERY speedy reply, 

The feed is below
`http://feeds.feedburner.com/blogspot/RLXA`

**Comment by bobby-brennan** [comment]
This actually exposed a bug with how `entry.link` was being chosen - the `alternate` link should always be preferred as of 2.10.8

Thanks for the report! Let me know if you're still seeing issues in the latest release.

**Comment by WorldWideWebb** [comment]
Just ran into this issue as well - I have a feed where each item has 2 link tags:

```
<link rel="alternate" type="text/html" href="http://page.html"/>

<link rel="enclosure" href="http://image.jpg" length="222384" type="image/jpg"/>
```

I need to be able to grab the second one (need to target the image url in that one. Is there a way to do that?

**Comment by bobby-brennan** [comment]
You can try using the [`customFields` option](https://github.com/bobby-brennan/rss-parser#custom-fields) with `keepArray: true`.

If that doesn't work, I'd be happy to accept a PR that adds this. Maybe set `item.links` on line 135 of `./lib/parser.js`

**Comment by lakshminarasimhan93** [comment]
> You can try using the [`customFields` option](https://github.com/bobby-brennan/rss-parser#custom-fields) with `keepArray: true`.
> 
> If that doesn't work, I'd be happy to accept a PR that adds this. Maybe set `item.links` on line 135 of `./lib/parser.js`

can you share the code snippet , tried as per document , but it it fetches only 1link tag
