### ISSUE TITLE
Potential issue with self closing tags or not completely parsing the feed

### ISSUE THREAD

**Issue by duluca** [bobby-brennan/rss-parser#43]
Great work on the parser, but it seems like it is not able to parse certain feeds. 

**Expected:** Full parsing of attributes and entries array
**Actual:** Partial parsing of attributes and only header info of entries

**Repro:**
Here's a live repo: https://runkit.com/duluca/rss-parser-parsing-issue-repro
or 
```
const {promisify} = require('util')

const parser = require('rss-parser')
const parseURLAsync = promisify(parser.parseURL)


parseURLAsync('http://www.rferl.org/mobapp/articles.xml')
.then((data) => {
    console.log(data)
})
```

**Comment by bobby-brennan** [comment]
I think this is an invalid feed. Each `<item>` seems to have an `<article>` tag, which isn't part of the RSS spec.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.rferl.org%2Fmobapp%2Farticles.xml
