### ISSUE TITLE
add xml close tag fix?

### ISSUE THREAD

**Issue by lqzhgood** [bobby-brennan/rss-parser#45]
some RSS/XML format is not standard.  not close tag ,like
`<img src="xxx">`
Fix this little problem in rss-parser ?

**Comment by bobby-brennan** [comment]
You can look at our [XML parser](https://github.com/Leonidas-from-XIV/node-xml2js), though it doesn't look like it supports unclosed tags. We just added the ability to set options for xml2js if you find an option that fixes this (maybe `strict: false`?). You can also try opening an issue there.

**Comment by lqzhgood** [comment]
I think you're right. please close this issues.
I will seek the support of  [XMLparser](https://github.com/Leonidas-from-XIV/node-xml2js)
