### ISSUE TITLE
How to only grab posts within a date range? 

### ISSUE THREAD

**Issue by dissoinfo** [bobby-brennan/rss-parser#47]
Eg. Only grab posts from a feed from the last 45 days.

Any way to do this via the library? Or an alternative suggestion?

Cheers, lovely plugin so far!

**Comment by bobby-brennan** [comment]
There's no way to do this in the library, but I think the below should work:

```js
const MAX_AGE = (new Date()).getTime() - 45 * 24 * 60 * 60 * 1000;
var recentEntries = result.feed.entries.filter(entry => {
  let date = new Date(entry.isoDate);
  return date.getTime() > MAX_AGE;
})
```
