### ISSUE TITLE
Should this be RSS compilant?

### ISSUE THREAD

**Issue by Takeno** [bobby-brennan/rss-parser#58]
Hello!

I'm using `rss-parser` but I've discovered that it ignores some official properties like `description` on item.
I know that it is extensible, but I think it should be able to read all _standard_ fields.

What do you think about?

Ref: https://validator.w3.org/feed/docs/rss2.html

**Comment by bobby-brennan** [comment]
Yup I agree, didn't realize we were missing the description field. I'm
surprised this is the first time someone noticed!

Feel free to send a PR that adds the standard fields here:

https://github.com/bobby-brennan/rss-parser/blob/master/lib/fields.js

Otherwise I'll try and get to it soon

**Comment by Takeno** [comment]
I'm using this module, so I'll try to find time to send PR this weekend :)

**Comment by bobby-brennan** [comment]
I've updated the fields we parse to extract almost everything in the RSS spec. The `description` field is actually contained in `content` and `contentSnippet`, where `contentSnippet` removes all HTML and unencodes HTML entities.

**Comment by Nettsentrisk** [comment]
Is it documented anywhere that item.description => item.content/contentSnippet? Was just scratching my head over this now and had to dig through the code to see that's what was going on :)

**Comment by BoKKeR** [comment]
I am not seeing the `description` being added in `content` or `contentSnippet` instead its accessible by `item.description`, which would be fine however the types are misleading

**Comment by skwee357** [comment]
I just spend two days debugging why my ```content``` field does not contain the full content as published in my RSS. Had to go to the code and look, that ```content``` is parsed as ```description``` if it's present.

Like @Nettsentrisk , I'm just wondering, why? I can't seem to find any official spec that says it should
