### ISSUE TITLE
reddit pubDate is nil

### ISSUE THREAD

**Issue by jhihguan** [bobby-brennan/rss-parser#63]
I'm trying 3.4.1 and using it to parse this reddit rss
https://www.reddit.com/r/mechmarket/new/.rss
but the pubDate is not existed. don't know if it's reddit rss format issue or parser issue?

I end up use customFields to parse `updated` as `pubDate`

**Comment by bobby-brennan** [comment]
Thanks for the report - 3.4.1 started using Atom's `published` field as `pubDate` instead of `updated`.

In 3.4.2 we've started using `updated` if `published` isn't available, so `pubDate` will always be available if either `updated` or `published` is set.

**Comment by jhihguan** [comment]
thank you, it fixed!
