### ISSUE TITLE
status 406 when parsing url

### ISSUE THREAD

**Issue by Kelanor** [bobby-brennan/rss-parser#64]
I'm trying to parse url
https://www.kommersant.ru/RSS/news.xml
but it returns me 406 status code. Maybe I forgot some extra headers, did I?

v. 3.4.2

P.s.: to avoid this error I use axios and iconv-lite combination and then use parseString method.

**Comment by bobby-brennan** [comment]
It looks like kommersant doesn't like the default `Accept` header of `application/rss+xml`. You can avoid the 406 by passing in custom headers:

```
let parser = new Parser({headers: {Accept: ''}});
```

Unfortunately the feed is encoded using windows-1251, which isn't supported natively in JavaScript, and we don't want add iconv as a dependency. You should stick with axios and iconv.
