### ISSUE TITLE
Feed not recognized as RSS 1 or 2

### ISSUE THREAD

**Issue by dinggewennuan** [bobby-brennan/rss-parser#69]
UnhandledPromiseRejectionWarning: Error: Feed not recognized as RSS 1 or 2
can you tell why ? thks

**Comment by bobby-brennan** [comment]
Can you share the URL?

**Comment by scottie** [comment]
would need site to see, try:
```
let parser = new Parser({
  defaultRSS: 2.0
});
```
If you know version.
