### ISSUE TITLE
Getting wrong encode

### ISSUE THREAD

**Issue by globalcircle** [bobby-brennan/rss-parser#7]
Hey, great job with rss-parser. But i when i try to catch some iso-8.. rss feed the typo isnt correct.. how can i fix this?

**Comment by bobby-brennan** [comment]
Are you using parseFile/parseURL?  These methods explicitly set the encoding to utf8.

I think you have two options:
* Read the file/url yourself, and use parseString
* Change the functions to accept an encoding object (happy to accept a PR)

If you prefer the latter, I think the best way to go is to allow users to pass in a string or an object as the first parameter, e.g.

```js
parseURL('https://www.reddit.com/.rss', callback)

parseURL({url: 'https://www.reddit.com', encoding: 'iso-8'}, callback)
```

would be equivalent.

**Comment by bobby-brennan** [comment]
Marking as fixed  - let me know if you're still having trouble.
