### ISSUE TITLE
problem validating feed url 

### ISSUE THREAD

**Issue by sachinjangid** [bobby-brennan/rss-parser#70]
I am making an api which validate that given feed url is valid or not. I tested that url with some online feed url checker. Those were giving xml parsing error for that url, but when I tried testing that url with `rss-parser` it successfully return data from the url.

Here is the url for testing http://independentbanker.org/feed/

I want to return error if there is any error while parsing XML data.

**Comment by bobby-brennan** [comment]
We don't do any validation - we will always do our best to parse the feed even when it's technically invalid.
