### ISSUE TITLE
Is there an option to define item limit or paging?

### ISSUE THREAD

**Issue by honb** [bobby-brennan/rss-parser#71]
I would like to retrieve a number of items at a time. Is this depend on FeedUrl or there is available option to define it in RSS Parser?

**Comment by bobby-brennan** [comment]
The HTTP request will always retrieve everything in the specified URL, so I don't think it makes sense to add pagination the library (you'll still have the overhead of a large network request and memory usage when parsing the XML).

I don't know of any feeds that offer pagination, but if it's a query parameter you can always pass as part of the URL.
