### ISSUE TITLE
Garbled parsing results of 'https://bbs.byr.cn/rss/topten'

### ISSUE THREAD

**Issue by Martin1024** [bobby-brennan/rss-parser#76]
Here is the RunKit test result:
![image](https://user-images.githubusercontent.com/24665332/46547841-d9bc1d80-c8ff-11e8-92f3-ff580ce660a7.png)
While there is no such problem in parsing other Chinese sources.

It will be very appreciated if you can help me with this problem.
(BTW, Thanks for solving the issues I submitted before.)

**Comment by bobby-brennan** [comment]
It looks like this feed uses the GBK character set, which is not supported. You should try downloading the feed using the `request` or `https` library, and then using [iconv](https://github.com/bnoordhuis/node-iconv) to convert the characters.
