### ISSUE TITLE
Uncaught (in promise) Error: Unexpected close tag ; Chrome User-Agent?

### ISSUE THREAD

**Issue by seevee** [bobby-brennan/rss-parser#80]
I am currently seeing inconsistent behavior across browsers using `rss-parser`.

I am testing with this RSS feed: http://www.marketwatch.com/rss/topstories

I do get the same error for all RSS feeds I have tried on the same domain.

Here is the relevant code, Vue-flavored:
```javascript
const CORS_PROXY = 'https://cors-anywhere.herokuapp.com/'

export default {
...
  mounted() {
    require('../../node_modules/rss-parser/dist/rss-parser.js')
    this.getFeeds()
  },

  methods: {
    async getFeeds() {
      const parser = new RSSParser({
        headers: {
          'User-Agent': 'rss-parser',
          'Cache-Control': 'no-cache',
          'Pragma': 'no-cache'
        },
        defaultRSS: 2.0,
        xml2js: {
          strict: true
        }
      })
      const feedRequests = this.$page.frontmatter.feeds.map(feed => {
        return parser.parseURL(CORS_PROXY + feed)
      })
      this.feeds = await Promise.all(feedRequests)
    }
  }
}
```

In Firefox, this will make a request that returns a valid RSS XML response; in Chrome, this is returning HTML, which makes rss-parser return the following error:

```
Uncaught (in promise) Error: Unexpected close tag
Line: 9
Column: 7
Char: >
    at error (rss-parser.js?e48f:12624)
    at strictFail (rss-parser.js?e48f:12648)
    at closeTag (rss-parser.js?e48f:12834)
    at SAXParser.write (rss-parser.js?e48f:13397)
    at Parser.parseString (rss-parser.js?e48f:11945)
    at Parser.eval [as parseString] (rss-parser.js?e48f:11620)
    at eval (rss-parser.js?e48f:8448)
    at new Promise (<anonymous>)
    at Parser.parseString (rss-parser.js?e48f:8447)
    at exports.IncomingMessage.eval (rss-parser.js?e48f:8520)
```

I can change all of the header attributes using the `headers` option, but `User-Agent` is the only one that will not change on Chrome (`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36`). I suspect this has something to do with what I'm seeing.

Is there any way I can work around this? I will provide more information if necessary.

**Comment by bobby-brennan** [comment]
Sounds like this is an issue with MarketWatch rather than rss-parser. Unless you can figure out how to get marketwatch to respond to an AJAX request with XML rather than HTML, I think you're out of luck.

Sorry I can't be of more help here.

**Comment by seevee** [comment]
Thanks for the reply @bobby-brennan, I figured as much.

At least this serves as a good example of why User Agent sniffing is nasty business.

**Comment by lastmjs** [comment]
Were you able to find a solution to this? I'm running into these issues too it seems...which is really sad

**Comment by bobby-brennan** [comment]
I would contact MarketWatch (or the provider of the RSS feed) to ask them what you need to do to guarantee an XML response.

Setting the `Accept` header to `text/xml` or `application/xml` might do the trick...

**Comment by lastmjs** [comment]
It's broken on a few feeds, quite a few it seems. This seems like a pretty large issue, unless I'm doing something wrong, but it's kind of making rss-parser unusable for quite a few feeds it seems

**Comment by lastmjs** [comment]
Setting the accept header didn't help, and I'm using the cors-anywhere url

**Comment by DavidASix** [comment]
@lastmjs I'm getting the same issue with multiple feeds.*.org links trying to grab podcast rss feeds.

**Comment by bobby-brennan** [comment]
Yes, this is an issue with the folks serving the RSS feeds. They see that the request is coming from a browser (by checking the `User-Agent` header) and decide to show an HTML page instead of RSS. Unfortunately you can't change the `User-Agent` header due to browser security.

The only solution here is to create a proxy that lets you set the `User-Agent` header, e.g. by setting an `X-Fake-User-Agent` header.

**Comment by seevee** [comment]
@bobby-brennan is absolutely right, it's the responsibility of the feed maintainer to implement RSS XML correctly. If I request XML, but they send HTML just because I'm using Chrome, then that's a gaffe on their part.

I have attempted to contact MarketWatch (which is owned by WSJ) about this and have not received a reply; we ended up using a different feed that is properly implemented. Our clients were satisfied, but everyone involved is still annoyed.

It is clear that a large number of RSS feed implementations were built without considering the [caveats of User-Agent sniffing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent). As clearly stated on MDN, it should be avoided whenever possible. I have had no luck finding any authoritative source that says otherwise.

There's only a few solutions to this for us developers making RSS clients:
- Enforce browsers that allow modifying the `User-Agent` header (please don't do this)
- Implement a proxy that allows you to overwrite the `User-Agent` header (effective, but gross)
- Hound the feed maintainers until they make the necessary adjustments (good luck)

It's likely not technical, but non-functional requirements that drive poorly-implemented solutions like this. The fault lies with the feed maintainers for using ill-advised techniques to approximate what should be a common standard.

**Comment by lastmjs** [comment]
I understand, thanks everyone. I have found a workaround for now: https://jsonp.afeld.me

It's working perfectly for every feed I've thrown at it so far, better than cors-anywhere.

**Comment by lastmjs** [comment]
I'd bet cors-anywhere could do whatever jsonp.afeld.me is doing, it would be good to contact that project to see if they can fix themselves for the RSS feeds that break.

**Comment by bobby-brennan** [comment]
As pointed out in #111, adding `?format=xml` may fix this issue for some feeds.
