### ISSUE TITLE
not passing multiple custom fields

### ISSUE THREAD

**Issue by scottie** [bobby-brennan/rss-parser#87]
Seems to only pass the last custom field passed to customFields.

ie:

```
let parser = new Parser({
    customFields: {
      item: ['s:type','s:type'], 
      item: ['s:vendor','s:vendor']
      item: ['summary','summary'],
      //item: ['s:tag','s:tag'],
      //item: ['s:variant','s:variant', {keepArray: true}] //<---

    }
  });
   
  parser.parseURL('https://kith.com/collections/all/products.atom', function(err, feed) {
    //console.log(feed.extendedDescription);

if(!err){
    feed.items.forEach(function(entry) {
        //console.log(entry['s:type']);
        //console.log(entry['s:vendor']);
        console.log(entry.summary);
        //console.log(entry['s:tag']);
        //console.log(entry['s:variant']);
        //console.log(entry);
        
    });
    //console.log(feed.items[7]['s:type']);
    //console.log(feed.items[7]['s:vendor']);
    console.log(feed.items[7]['summary']);
    //console.log(feed.items[7]['s:tag']);
    //console.log(feed.items[5]['s:variant']['s:price'][0]['_']);
    //console.log(feed.items[5].summary);
   }else{
       console.log(err.message);
   };
```

Seems to only pass THE LAST item added to "customFields".
's:vendor' will show undefined untill "item: ['summary','summary']," is commented out then it will work.

**Comment by bobby-brennan** [comment]
You syntax isn't quite right:
```js
let parser = new Parser({
    customFields: {
      item: [
        ['s:type','s:type'], 
        ['s:vendor','s:vendor']
        ['summary','summary'],
        ['s:tag','s:tag'],
        ['s:variant','s:variant', {keepArray: true}] //<---
    }
  });
```

And since you're not trying to rename fields, it can be even simpler:

```js
let parser = new Parser({
    customFields: {
      item: [
        's:type', 
        's:vendor',
        'summary',
        's:tag'],
        ['s:variant','s:variant', {keepArray: true}] //<---
    }
  });
```

**Comment by bobby-brennan** [comment]
(Also note that your input above, which has multiple `item` fields, isn't really a valid JS object - in JS, you can only specify one value per key).

**Comment by scottie** [comment]
thanks mate sorry for the confusion i see now :)

**Comment by scottie** [comment]
> 
> 
> (Also note that your input above, which has multiple `item` fields, isn't really a valid JS object - in JS, you can only specify one value per key).

tell that to the RSS feed i am parsing ...

**Comment by rashnk** [comment]
I'm bit confused. Why thumbnail is not returned from this feed [http://www.kasargodvartha.com/feeds/posts/default](http://www.kasargodvartha.com/feeds/posts/default)

this is my config

```
let parser = new Parser({
  customFields: {
    item: ["story", ["thumbnail", "image", { keepArray: true }]]
  }
});
```

anything wrong ?

**Comment by bobby-brennan** [comment]
I see tags called `media:thumbnail` and `gd:image` in that feed - try using those terms.

**Comment by bobby-brennan** [comment]
I also don't see anything called "story". It should be:
```js
let parser = new Parser({
  customFields: {
    item: ["media:thumbnail", "gd:image"]
  }
});
```

**Comment by rashnk** [comment]
sorry @bobby-brennan, that was my mistake, I can access the media thumbnail now,
Im working with some news sites rss/atom feeds, that has some different fields for content like **story** , **summary**
so this is my config now, 

```
  customFields: {
    item: [
      "story",
      ["summary", "contentSnippet"],
      ["media:thumbnail", "thumbnail"]
    ]
```
and i have to get the content like this `this.news["contentSnippet"]["_"];` , is there any way to get the content directly to the key like title, author,etc
