### ISSUE TITLE
ERROR TypeError: rss_parser_dist_rss_parser_min_js__WEBPACK_IMPORTED_MODULE_3__.RSSParser is not a constructor  

### ISSUE THREAD

**Issue by anshulsinha1101** [bobby-brennan/rss-parser#90]
I am using rss-parser in my Angular project and in .ts file i am writing below code and inside ngOnInit() my code is written i am getting error

ERROR TypeError: rss_parser_dist_rss_parser_min_js__WEBPACK_IMPORTED_MODULE_3__.RSSParser is not a constructor  

import { RSSParser } from 'rss-parser/dist/rss-parser.min.js';
 ngOnInit() {
const CORS_PROXY = "https://cors-anywhere.herokuapp.com/"
 
let parser = new RSSParser();
parser.parseURL(CORS_PROXY + 'https://www.reddit.com/.rss', function(err, feed) {
  console.log(feed.title);
  feed.items.forEach(function(entry) {
    console.log(entry.title + ':' + entry.link);
  })
})
}
Thanks in Advance

**Comment by anshulsinha1101** [comment]
Please let me know if my approach is wrong

**Comment by anshulsinha1101** [comment]
@bobby-brennan i am not able to import RSSParser from 'rss-parser' its showing error.
/node_modules/rss-parser/index"' has no exported member 'RSSParser'.

**Comment by anshulsinha1101** [comment]
@Fazendaaa could you please help

**Comment by feimosi** [comment]
I experience the same problem after upgrading from `3.5.4` to `3.6.2`

**Comment by Dzhuneyt** [comment]
I am experiencing the same issue.

**Comment by Dzhuneyt** [comment]
Solved this by suppressing TypeScript compilation errors. Not the most elegant solution but works for me:

```
import * as Parser from "rss-parser";
// @ts-ignore
let local = new Parser();
```

**Comment by anshulsinha1101** [comment]
@Dzhuneyt 
I am getting below error during compile time 
could you please share your full code here
```
ERROR in ./node_modules/rss-parser/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\***\***\***\node_modules\rss-parser'
ERROR in ./node_modules/rss-parser/index.js
Module not found: Error: Can't resolve 'http' in 'C:\Users\***\***\***\node_modules\rss-parser'
ERROR in ./node_modules/rss-parser/index.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\***\***\***\node_modules\rss-parser'
```
