### ISSUE TITLE
Frontend usage: Internet Explorer Support (IE11)

### ISSUE THREAD

**Issue by dollarusername2** [bobby-brennan/rss-parser#91]
I am using the project for a frontend website based on bootstrap to show rss content.
However I am experiencing issues with IE11 (sorry, company restrictions :-/ ).

Works perfect in Chrome and Firefox, throws errors in Internet Explorer 11 (11.0.105 for me).

1. First I got an error that Object.assign() is not defined --> Fixed by usindg a polyfill, see code
2. Then I got an error that promise is not defined --> Fixed by importing you polyfill promise script
3. Now I get an error `SCRIPT5007: The property "title" of a undefined or NULL reference cannot be retrieved . test.html (43,4) ` (tranlated by me, sorry)

I build a minimal example `test.html` that does work in Chrome, but not in Internet Explorer, any ideas?

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
  <body>
    <span>Hello World.</span>
	
	<script src="rss-parser.js"></script>
	<script src="polyfill.js"></script>
	<script>
	
	// Object.assign() polyfill for Internet Explorer
	if (typeof Object.assign != 'function') {
	  Object.assign = function(target) {
		'use strict';
		if (target == null) {
		  throw new TypeError('Cannot convert undefined or null to object');
		}

		target = Object(target);
		for (var index = 1; index < arguments.length; index++) {
		  var source = arguments[index];
		  if (source != null) {
			for (var key in source) {
			  if (Object.prototype.hasOwnProperty.call(source, key)) {
				target[key] = source[key];
			  }
			}
		  }
		}
		return target;
	  };
	}
	
	// Note: some RSS feeds can't be loaded in the browser due to CORS security.
	// To get around this, you can use a proxy.
	const CORS_PROXY = "https://cors-anywhere.herokuapp.com/"

	let parser = new RSSParser();
	parser.parseURL(CORS_PROXY + 'https://www.reddit.com/.rss', function(err, feed) {
	  console.log(feed.title);
	  feed.items.forEach(function(entry) {
		console.log(entry.title + ':' + entry.link);
	  })
	})

	</script>
  </body>
</html>
```

**Comment by bobby-brennan** [comment]
Hi there,

Sorry for the delay. It looks like `feed` might be undefined - try checking `err` to see if there are any details there.
