### ISSUE TITLE
Redirect. Feed not recognized as RSS 1 or 2.

### ISSUE THREAD

**Issue by azotklas** [bobby-brennan/rss-parser#92]
Hi. I use rss-parser v.3.6.2
I have a link (HTTP://www.site1.com/example?param=78da4d90) that redirects to another link with RSS feed (HTTPS://www.site2.com/feed).

```
const Parser = require('rss-parser');
const parser = new Parser();
parser.parseURL("HTTP://www.site1.com/example?param=78da4d90", function (err, feed) {
  ERROR: Feed not recognized as RSS 1 or 2
}
```

How can I fix this problem? Maybe use other modules in conjunction with 'rss-parser'?
Does anyone have any ideas?

**Comment by azotklas** [comment]
On the page HTTP://www.site1.com/example?param=78da4d90
there is a code on the page:
<script language="javascript" type="text/javascript">
       var query = window.location.search.substring(1);
       window.location = "site1.php?" + query;
</script>

**Comment by bobby-brennan** [comment]
JavaScript redirects aren't supported. The server needs to return an HTTP redirect (301 or 302).

The only way to detect the JS redirect is to use a headless browser, which is major overkill for RSS parsing.

Sorry we can't be of more help here.
