### ISSUE TITLE
Removal of zero width no-break space

### ISSUE THREAD

**Issue by MorningSleeper** [bobby-brennan/rss-parser#95]
Hi, using 3.6.2 of rss-parser and 0.4.19 of xml2js. I intermittently get following error when trying to use parseURL on the SEC's [feed](https://www.sec.gov/Archives/edgar/xbrlrss.all.xml). They are of little help and just wrote that it happens sometimes.

```
Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: �

```
According to following [page](https://www.screenaware.com/en/blog/xml2js-sax-js-non-whitespace-before-first-tag
) that same error can be caused by not removing a zero width no-break space before passing the data on to xml2js. Does your program automatically remove such before passing to xml2js or can I tell it to do so somehow? If not, could I alternatively try using request to get feed into a string, remove character, if it exists, as suggested in page above, then use your modules parseString instead of parseURL?

Thanks.

**Comment by bobby-brennan** [comment]
If xml2js can handle this, you might be able to do something with [xml2js passthrough options](https://github.com/bobby-brennan/rss-parser#xml2js-passthrough)

Otherwise I'd happily accept a PR that adds a `stripWhitespace` option

**Comment by MorningSleeper** [comment]
Thanks for your reply. The only xml2js option that I see listed that seems relevant is includeWhiteChars and it is already set to false by default. I am not competent enough in programming to submit a PR so will try to retrieve the feed with request and remove the character before passing it to parseString to see if that works.

**Comment by zengxiaoluan** [comment]
我在这里找到了解决方法：https://stackoverflow.com/questions/34783452/cannot-parse-xml-error-non-whitespace-before-first-tag-line-0-column-1-cha

**Comment by balibebas** [comment]
本当に問題を解決する方法: https://habd.as/post/show-latest-posts-github-profile/
