### ISSUE TITLE
getaddrinfo ENOTFOUND error on particular domain

### ISSUE THREAD

**Issue by Alchete** [bobby-brennan/rss-parser#97]
In a parse for an rss stream, every time their RSS feed updates I get the "getaddrinfo ENOTFOUND" error.  Two examples below:

monitorRSS error - http://ir.tesla.com/rss/news-releases.xml - Error: getaddrinfo ENOTFOUND ir.tesla.com ir.tesla.com:80
monitorRSS error - http://ir.tesla.com/rss/sec-filings.xml - Error: getaddrinfo ENOTFOUND ir.tesla.com ir.tesla.com:80

As such, I miss their new rss items.  This is the only domain that throws this error for me.  Any ideas what could be happening?

**Comment by bobby-brennan** [comment]
These feeds parse fine for me. My guess is that either `ir.tesla.com` was down for a minute, or it has something to do with the configuration of you local network/firewall.

Sorry I can't be of more help - good luck!
